---

codecov:
  notify:
    after_n_builds: 20  # The number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: >-  # notsecret  # repo-scoped, upload-only, stability in fork PRs
    0b255cf3-ed51-43a8-b7df-8a9f23da39b1

comment:
  require_changes: true

coverage:
  range: 99.34..100
  status:
    patch:
      default:
        target: 100%
        flags:
        - pytest
    project:
      default:
        target: 87.5%  # 100%
      lib:
        flags:
        - pytest
        paths:
        - propcache/
        target: 100%
      packaging:
        paths:
        - packaging/
        target: 75.24%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 98.2%  # 100%
      typing:
        flags:
        - MyPy
        target: 77.5%  # 100%

...
