from propcache import cached_property, under_cached_property

class TestUnderCachedProperty:
    def __init__(self) -> None: ...
    @under_cached_property
    def prop(self) -> int: ...
    @under_cached_property
    def prop2(self) -> str: ...

class TestCachedProperty:
    def __init__(self) -> None: ...
    @cached_property
    def prop(self) -> int: ...
    @cached_property
    def prop2(self) -> str: ...

class TestUnderCachedPropertyAssignment:
    def __init__(self) -> None: ...
    @cached_property
    def prop(self) -> int: ...
